name: Publish Docker image
on:
  push:
    paths:
      - '**'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_PAT }}

      - name: Get Date of Base Build
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY-MM-DD'

      - name: Prepare Environment Variables
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Push to GitHub Packages for Base Build
        uses: docker/build-push-action@v2.3.0
        with:
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:base-${{ env.RELEASE_VERSION }}
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:base-latest
          push: true
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.time }}
            BUILD_TAG=base-${{ env.RELEASE_VERSION }}
            CDPY=true